// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVZWmpiYgMWPaO95liR5Sivi50c5o0wY4',
    appId: '1:561905173639:web:fbf1936b15322b8ee16422',
    messagingSenderId: '561905173639',
    projectId: 'resqconnect-6f4bd',
    authDomain: 'resqconnect-6f4bd.firebaseapp.com',
    storageBucket: 'resqconnect-6f4bd.firebasestorage.app',
    measurementId: 'G-L5TKTJ066W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBp0g09LMWvnLkNS0FpxnLC0RX5xo8YGoY',
    appId: '1:561905173639:android:a666dad62355701de16422',
    messagingSenderId: '561905173639',
    projectId: 'resqconnect-6f4bd',
    storageBucket: 'resqconnect-6f4bd.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbf-AX9JtvlsoMHwjH9suihHKSTOdADAU',
    appId: '1:561905173639:ios:d90fcf89b11fd894e16422',
    messagingSenderId: '561905173639',
    projectId: 'resqconnect-6f4bd',
    storageBucket: 'resqconnect-6f4bd.firebasestorage.app',
    iosBundleId: 'com.resqconnect.resqconnect',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbf-AX9JtvlsoMHwjH9suihHKSTOdADAU',
    appId: '1:561905173639:ios:d90fcf89b11fd894e16422',
    messagingSenderId: '561905173639',
    projectId: 'resqconnect-6f4bd',
    storageBucket: 'resqconnect-6f4bd.firebasestorage.app',
    iosBundleId: 'com.resqconnect.resqconnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVZWmpiYgMWPaO95liR5Sivi50c5o0wY4',
    appId: '1:561905173639:web:3b405679a27b26cfe16422',
    messagingSenderId: '561905173639',
    projectId: 'resqconnect-6f4bd',
    authDomain: 'resqconnect-6f4bd.firebaseapp.com',
    storageBucket: 'resqconnect-6f4bd.firebasestorage.app',
    measurementId: 'G-13LW3HRRNF',
  );
}
